trigger:
  branches:
    include:
    - "master"
  paths:
    include:
    - src/*
    - tests/*

pool:
  vmImage: 'ubuntu-18.04'

steps:
- bash: |
    set -e
    utils/test.sh
    utils/linter.sh
  workingDirectory: $(Build.SourcesDirectory)
  displayName: Python Checks

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage.xml'
    pathToSources: '$(Build.SourcesDirectory)/Calculator'
    failIfCoverageEmpty: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Build.SourcesDirectory)/pytest-results.xml' 
    failTaskOnFailedTests: true